### ISSUE TITLE
.document/udev の扱いについて

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_robot#3]
udevに関するメモとlinux用設定ファイルがおもむろに.document/udevの中に入っていると思うのですが、
.ファイル(隠しファイル)以外になんの説明もなくおいてあるのは不親切であるかと思います。

かと言って解決策としてこれをcatkinパッケージに含めてインストールさせるのはやり過かな、とも思っています。
実機用のファイルといえばそうなので、このリポジトリにあっても不自然では無いですが、
きちんとしたドキュメントを整備するか、パッケージに含めるか、あるいは別の解決法を模索したいなと思います。

**Comment by AriYu** [comment]
@forno 
すいません。
もとの`third_robot_pkg`のREADMEでは説明しててそこからリンク貼ってたのですが、忘れてました。
ただ、どういう扱いにするかは議論したほうがいいかもしれません。

**Comment by forno** [comment]
誰も対応してないのでこっそり閉じる
