### ISSUE TITLE
imcs01_driver ・・・は存在していても良いのでしょうか

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_robot#5]
前から少し気になっていましたが、このリポジトリに `/cirkit_unit03_driver/include/ThirdRobotInterface/imcs01_driver` は存在していて良いのでしょうか。
仮に良いとして、この位置は如何なのでしょうか。

詳しくは存じ上げないのでわからないことが多いのですが、imcs01_driverはユーザのシステムにはインストールできないものなのでしょうか。
また、仮にそうであっても、分量が多いため何か別のパッケージに切り分けて依存させたいように思います。

**Comment by AriYu** [comment]
@forno 
著作権的にまずいと思っています。
しかし配布元がzipしか無い上に少しコードを変更してるため配布元そのままだとビルドできないという問題もあります。配布されているドライバーにライセンスの記述なし…
そもそもimcs01を使うのを変更すればいいのですが。

**Comment by forno** [comment]
コードの著作権に関しては、バイナリ、ソース共に配布物に含まなければ基本的に無視できはずですので、
パッチを配布する形にすればその点回避できるかと思いますが、この間の説明を少し聞いた限りでは問題は根深いようですね。
何気にimcs01のディレクトリ内からThirdRobotというgrepが引っかかってるのも気になったり気にならなかったりします。
ゆっくり解決してゆくか、imcs01を投げ捨てるのが良いのでしょうね。

**Comment by AriYu** [comment]
* 変なドライバーに依存しない
* エンコーダが最低でも3つ読める（4000 pulse/secくらい）
* アナログ出力もできる
* できればUSBだけで接続できる
これを満たせるようなボードがあれば置き換えましょう

**Comment by forno** [comment]
wontfixとして一旦閉じます．
