### ISSUE TITLE
driver にて radio と名の付くファイルが全く使用されていないようです

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_robot#7]
暇だったのでついついリファクタ作業を始めたのですが、全くビルドや実行に関係のないradioと名の付くファイルが存在するようです。~~手を付けた作業が全部無駄だったのか…と軽いショックを受けました。~~

この全く使用されていないファイルは必要なければ削除しようかと思うのですが、なにか思うところがあって残しているのでしょうか？
とはいえ、Gitを採用しているのでわざわざ必要のないファイルを残しておく必要は無いかと思います。いつでも復元できますので。

このファイルは何で、これからどうするのかを教えていただけると幸いです。

**Comment by AriYu** [comment]
@forno 
そのファイルはS（先輩）が書いたもので、私もわかっていません。

**Comment by forno** [comment]
ではとりあえず消しましょう。このファイルは消してもなんの影響も及ぼしません。

**Comment by forno** [comment]
あにゃーん。　せっかくコミットメッセージでクローズするを試そうと計画していたのに閉じられちゃったw
あれですね。相談事(決めごと)とリポジトリに変更を加えるたぐいのIssueって見分けられるようにしたほうが良いのでしょうか。　それとも、結論が出たらとりあえず閉じる方針で行きしょうか。

この話題でIssue立ててきますん。

**Comment by AriYu** [comment]
すいません。勝手に閉じちゃいました。
Reopenしていいです。

それはそれでwholeの方にイシューたててくれませんか？

2016年11月17日(木) 23:35 Doi Yusuke notifications@github.com:

**Comment by AriYu** [comment]
出来てました。
すいません。

2016年11月17日(木) 23:53 tech Arita tafutech@gmail.com:
