### ISSUE TITLE
add_cirkit_unit03_driver ブランチについて

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_robot#9]
全力でdriverをリファクタリングしておいてなんですが、
add_cirkit_unit03_driver ブランチというブランチが放置されていることに気が付きました。
このこにはこの子の歴史があるご様子。一体どのようなブランチなのでしょうか。

**Comment by forno** [comment]
手元のブランチを切ってお試しにマージして確認してみたところ、 `third_robot_bringup` パッケージの開発ブランチだったようです。

変更ファイル数にして6ファイル。.gitignoreのみにコンフリクト。
launchファイルだけ入っているように見受けられます。
内容物は以下の感じです。

``` bash
/cirkit_unit03_robot$ ls third_robot_bringup/*
third_robot_bringup/CMakeLists.txt  third_robot_bringup/package.xml

third_robot_bringup/launch:
description_only.launch  sensor_bringup.launch  third_robot_bringup.launch
```

**Comment by AriYu** [comment]
@forno 
すでにmasterにマージされてたはずなので、消し忘れです。

**Comment by AriYu** [comment]
うーん、よく見たらマージされていないですね。もうちょっと待ってください。

**Comment by AriYu** [comment]
@forno 
内容を見る限り特に新しいわけでも無いので、消していいです。

**Comment by forno** [comment]
@AriYu 
ありがとうございます。
見通しのため削除しておきます。
